### ISSUE TITLE
Broken links for vendor/tech artifacts

### ISSUE THREAD

**Issue by ohofmann** [ghga-de/ghga-metadata-schema#166] opened 2024-10-09 02:04 UTC
I am trying to read up on the metadata requirements for GHGA but noticed that links for the JSON schema, GraphQL and Co listed in https://github.com/ghga-de/ghga-metadata-schema lead to 404s. Could these artifacts be created from the current YAML schema?

**Comment by sbilge** [comment] 2024-10-21 15:24
The issue is fixed via #167.

**Closed by sbilge** 2024-10-21 15:24 UTC
Labels: bug
